version: "3"
services:
  nginx:
    image: nginx:alpine
    links:
      - php-fpm
    ports:
      - "127.0.0.1:8080-8099:8080-8099"
    volumes:
      # - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx.conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx/:rw
      - ./www:/usr/share/nginx/html:ro
  php-fpm:
    image: yyqqing/php-fpm
    links:
      - mysql
      - redis
    ports:
      - "9000"
    volumes:
      - ./www:/var/www/html:ro
  mysql:
    image: yyqqing/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./data/mysql:/var/lib/mysql:rw
  redis:
    image: yyqqing/redis:alpine
    ports:
      - "26379:6379"
# networks:
#   frontend:
#   backend: