version: "3.1"
services:
  nginx:
    image: nginx:alpine
    links:
      - php-fpm
    ports:
      - "127.0.0.1:8080-8099:8080-8099"
    volumes:
      # - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx.conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx/:rw
      - ./www:/usr/share/nginx/html:ro
    networks:
      - backend
  php-fpm:
    image: yyqqing/php-fpm
    links:
      - mysql
      - redis
    ports:
      - "9000"
    volumes:
      - ./www:/var/www/html:ro
      - ./logs/php-fpm/:/var/log:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - backend
  mysql:
    image: yyqqing/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - backend
  redis:
    image: yyqqing/redis
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    name: nginx_default
    driver: bridge
