#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
echo "Current working directory: '"$(pwd)"'"
export COMPOSER_HOME=~/.config/composer
export COMPOSER_CACHE_DIR=~/.cache/composer 
docker run --rm --interactive --tty --env COMPOSER_HOME --env COMPOSER_CACHE_DIR --volume $PWD:/app -v ~/.ssh:/root/.ssh  -v $COMPOSER_HOME:$COMPOSER_HOME -v $COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR yyqqing/composer $@
