#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
echo "Current working directory: '"$(pwd)"'"
docker run --tty --rm --network=nginx_default -v $(pwd):/app -v ~/.ssh:/root/.ssh -w /app yyqqing/php php $@
