#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
echo "PHPCS Current working directory: '"$(pwd)"'"
docker run --tty --rm -v $(pwd):/app -v ~/.ssh:/root/.ssh -w /app yyqqing/php phpcbf $@
